### PR TITLE
Updated docker-compose tag to match docker hub

### PR DESCRIPTION
**Pull request by shaun-hope**
The docker-compose.yml is referencing tag "3.0.0" but the actual tag in Docker Hub is "v3.0.0"

### CODE REVIEW

**Comment by mountaindude** [comment]
I know - the versioning has been a mess...
At least inconsistent - some versions in some Butler tools have had a Docker image version number prefixed by a "v".

That ends today, going forward the versioning scheme of all Butler tools will be:

Major.Minor.Patch

Other Butler tools will be updated as new releases are coming, but the good news is that the App Duplicator 3.0.2 is [out today](https://github.com/ptarmiganlabs/butler-app-duplicator/releases/tag/3.0.2), following the new versioning scheme.

Sorry again about the inconvenience.

**Comment by shaun-hope** [comment]
Hi, no worries - I very much appreciate your contributions around DevOps and Qlik, as I'm working to bring more app governance to our organization.  As I work through implementations (and working through your documentation which is very good), if I find minor typos or the like, would you prefer I submit suggestions/fixes through pull requests, or just enhancement requests?

**Comment by mountaindude** [comment]
PRs are always appreciated of course - the more complete the better :)
Just for the record: I have no need what so ever to do everything myself,
rather the contrary. As fun it is to work on this kind of stuff, good ideas
usually come when working/talking/thinking with others.

Quick note about the various Butler tools: Some of them have not been
updated in a while (like the original Butler), and this might show when you
implement them.
I can't think of any major issues, just something to be aware of. I try to
work on all of them when time allows, but as the family grows some members
might end up being somewhat neglected.

Out of curiosity, do you implement them using Docker or native?

**Comment by shaun-hope** [comment]
I’ve just started to implement using Docker – the App Duplicator was the first Butler tool I’ve implemented, but also plan to implement Butler SOS via Docker in the coming weeks.

It’s taken a little while mainly because I’ve got limited experience with Docker plus had to reinstall a lot of stuff on a new laptop, plus fight with out local IT proxy rules 😊  But, it’s not hard to see why people very quickly become fans of containerization for deployment.

I’ll keep you posted on progress using Docker.


Shaun Hope
M  +1 (250) 507-2154

**Comment by mountaindude** [comment]
Cool, sounds like you are making the right choices.
I've found it simply transformative going to a containerised way of
working... All those "works-here-but-not-there" problems are just gone.
Very nice.

From here I plan to make sure the Butler tools work also in the cloud
providers' Docker environments. If you have Sense on Google or AWS or Azure
servers - why not run Butler on their container services? Much simpler, no
extra server just for monitoring, redundancy etc etc. Lots' of easy wins
there.

Anyways - labour day here today - nice with a day off! :)

Cheers,
Göran

**Pull request closed without merging**
